import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "EasyNotes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
